name: Daily and Push Playwright Test Run

on:
  push:
    branches: main  
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: npm install

      - name: Run PLaywright tests
        run: npx playwright test
